[tool.black]
line-length = 100
target-version = ['py37']

[tool.flake8]
exclude = ['.git','__pycache__','env']
max-line-length = 100
max-complexity = 12
ignore = ['N803','N806','N802','N801','E203','E231','E712','C417','W503','C408']

[tool.mypy]
python_version = "3.7"
disallow_untyped_defs = true
ignore_missing_imports = true
ignore_missing_imports_per_module = true
disable_error_code = 'annotation-unchecked'
exclude = ['(?x)(^env|^src/thefittest/tests)']